/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CostDialog.java
 *
 * Created on 07/07/2009, 01:10:09
 */
package pfinance.view;

import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import pfinance.controller.FabricaGerenciador;
import pfinance.controller.GerenciadorCaixa;
import pfinance.controller.GerenciadorObjetos;
import pfinance.controller.GerenciadorSessao;
import pfinance.model.entity.Caixa;
import pfinance.model.entity.Categoria;
import pfinance.model.entity.MesRef;
import pfinance.model.entity.TipoConta;
import pfinance.utils.Calendario;
import pfinance.utils.Utils;

/**
 *
 * @author higorlandia
 */
public class FormLancamentoCaixa extends javax.swing.JDialog {

    private GerenciadorSessao gerSessao;
    private GerenciadorCaixa gerCaixa;
    private GerenciadorObjetos gerObjetos;
    private Caixa objetoCorrente;
    private boolean modificado;

    /** Creates new form CostDialog */
    public FormLancamentoCaixa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbTipoOperacao = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cbTipoConta = new javax.swing.JComboBox();
        buttonTipoConta = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbCategoria = new javax.swing.JComboBox();
        buttonCategoria = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbMesRef = new javax.swing.JComboBox();
        buttonMesRef = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        buttonSave = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        txtValorPago = new javax.swing.JFormattedTextField();
        txtValorPrevisto = new javax.swing.JFormattedTextField();
        txtDataPrevista = new javax.swing.JFormattedTextField();
        txtDataPagto = new javax.swing.JFormattedTextField();
        dpDataPrevista = new javax.swing.JButton();
        dpDataPrevista1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Tipo Operacao:");

        cbTipoOperacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CREDITO", "DEBITO" }));

        jLabel2.setText("Tipo Custo:");

        buttonTipoConta.setText("...");
        buttonTipoConta.setToolTipText("Inserir novo...");

        jLabel3.setText("Categoria:");

        cbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriaActionPerformed(evt);
            }
        });

        buttonCategoria.setText("...");
        buttonCategoria.setToolTipText("Inserir novo...");

        jLabel4.setText("Mes Ref:");

        buttonMesRef.setText("...");
        buttonMesRef.setToolTipText("Inserir novo...");

        jLabel5.setText("Data Prevista:");

        jLabel6.setText("Valor Previsto:");

        jLabel7.setText("Data Pagto");

        jLabel8.setText("Valor Pago:");

        buttonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/accept.png"))); // NOI18N
        buttonSave.setText("Salvar");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        buttonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/cross.png"))); // NOI18N
        buttonCancel.setText("Cancelar");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        dpDataPrevista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/calendar.png"))); // NOI18N
        dpDataPrevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpDataPrevistaActionPerformed(evt);
            }
        });

        dpDataPrevista1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/calendar.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbMesRef, javax.swing.GroupLayout.Alignment.LEADING, 0, 249, Short.MAX_VALUE)
                            .addComponent(cbCategoria, javax.swing.GroupLayout.Alignment.LEADING, 0, 249, Short.MAX_VALUE)
                            .addComponent(cbTipoConta, 0, 249, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonMesRef)
                            .addComponent(buttonTipoConta)
                            .addComponent(buttonCategoria)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbTipoOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                        .addComponent(buttonCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDataPagto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValorPago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dpDataPrevista1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDataPrevista, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValorPrevisto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dpDataPrevista, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbTipoOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTipoConta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCategoria))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMesRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonMesRef))))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(dpDataPrevista)
                    .addComponent(txtDataPrevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtValorPrevisto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(dpDataPrevista1)
                    .addComponent(txtDataPagto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSave)
                    .addComponent(buttonCancel))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCategoriaActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        // TODO add your handling code here:
        this.salvar(this.getFormData());
        dispose();
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void dpDataPrevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpDataPrevistaActionPerformed
        // TODO add your handling code here:
        Calendario cal = new Calendario(new javax.swing.JFrame(), true);
        cal.setLocation(((javax.swing.JButton) evt.getSource()).getLocation());
        cal.setVisible(true);
        cal.dispose();
    }//GEN-LAST:event_dpDataPrevistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                FormLancamentoCaixa dialog = new FormLancamentoCaixa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonCategoria;
    private javax.swing.JButton buttonMesRef;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonTipoConta;
    private javax.swing.JComboBox cbCategoria;
    private javax.swing.JComboBox cbMesRef;
    private javax.swing.JComboBox cbTipoConta;
    private javax.swing.JComboBox cbTipoOperacao;
    private javax.swing.JButton dpDataPrevista;
    private javax.swing.JButton dpDataPrevista1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JFormattedTextField txtDataPagto;
    private javax.swing.JFormattedTextField txtDataPrevista;
    private javax.swing.JFormattedTextField txtValorPago;
    private javax.swing.JFormattedTextField txtValorPrevisto;
    // End of variables declaration//GEN-END:variables

    public void init() {
        // configura os campos
        Utils.campoDinheiro(txtValorPago);
        Utils.campoDinheiro(txtValorPrevisto);

        //Carrega as fabricas
        this.gerSessao = FabricaGerenciador.getInstancia().get(GerenciadorSessao.class);
        this.gerCaixa = FabricaGerenciador.getInstancia().get(GerenciadorCaixa.class);
        this.gerObjetos = FabricaGerenciador.getInstancia().get(GerenciadorObjetos.class);

        //Cria objeto
        this.objetoCorrente = new Caixa();

        //Carrega os itens da interface
        this.carregaCategorias();
        this.carregaMesesRef();
        this.carregaTiposContas();





    }

    public void carregaTiposContas() {
        List<TipoConta> lista = this.gerObjetos.getTiposConta();
        for (TipoConta obj : lista) {
            this.cbTipoConta.addItem(obj);
        }
    }

    public void carregaCategorias() {
        List<Categoria> lista = this.gerObjetos.getCategorias();
        for (Categoria obj : lista) {
            this.cbCategoria.addItem(obj);
        }
    }

    public void carregaMesesRef() {
        MesRef sel = null;
        List<MesRef> lista = this.gerObjetos.getMesesRef();
        for (MesRef obj : lista) {
            if(this.gerSessao.getMesRefAtivo().getId().equals(obj.getId()))
                sel = obj;
            this.cbMesRef.addItem(obj);
        }
        this.cbMesRef.setSelectedItem(sel);
    }

    public void editar(Caixa obj) {
        this.setObjetoCorrente(obj);
        this.cbCategoria.setSelectedItem((Categoria)obj.getCategoria());
        this.cbMesRef.setSelectedItem((MesRef) obj.getMesRefByMesRefId());
        this.cbTipoConta.setSelectedItem((TipoConta) obj.getTipoConta());
        this.txtDataPagto.setText(Utils.formataData(obj.getDataPagamento()));
        this.txtDataPrevista.setText(Utils.formataData(obj.getDataInicio()));
        this.txtValorPrevisto.setText(Utils.formataDinheiro(obj.getValorEsperado()));
        this.txtValorPago.setText(Utils.formataDinheiro(obj.getValorPago()));
        String op = (obj.getTipoOperacao().equalsIgnoreCase("D")) ? "DEBITO"  : "CREDITO";
        this.cbTipoOperacao.setSelectedItem(op);
    }

    private void salvar(Caixa obj) {
        this.modificado = true;
    }

    private Caixa getFormData() {
        Categoria cat = (Categoria) this.cbCategoria.getSelectedItem();
        this.objetoCorrente.setCategoria(cat);
        TipoConta tc = (TipoConta) this.cbTipoConta.getSelectedItem();
        this.objetoCorrente.setTipoConta(tc);
        MesRef mr = (MesRef) this.cbMesRef.getSelectedItem();
        this.objetoCorrente.setMesRefByMesRefId(mr);
        String op = (String) this.cbTipoOperacao.getSelectedItem();
        if(op.equalsIgnoreCase("CREDITO"))
            this.objetoCorrente.setTipoOperacao("C");
        else
            this.objetoCorrente.setTipoOperacao("D");
        this.objetoCorrente.setDataInicio(Utils.formataData(this.txtDataPrevista.getText().toString()));
        this.objetoCorrente.setDataCadastro(Utils.dataAtual());
        this.objetoCorrente.setDocumento(gerSessao.getDocumentoAtivo());
        this.objetoCorrente.setUltimaAtualizacao(Utils.dataAtual());
        this.objetoCorrente.setValorEsperado(Utils.formataDinheiro(this.txtValorPrevisto.getText()));
        this.objetoCorrente.setValorPago(Utils.formataDinheiro(this.txtValorPago.getText()));
        return objetoCorrente;
    }

    public boolean isModificado() {
        return this.modificado;
    }

    public Caixa getObjetoCorrente() {
        return this.objetoCorrente;
    }

    /**
     * @param objetoCorrente the objetoCorrente to set
     */
    public void setObjetoCorrente(Caixa objetoCorrente) {
        this.objetoCorrente = objetoCorrente;
    }

    /**
     * @param modificado the modificado to set
     */
    public void setModificado(boolean modificado) {
        this.modificado = modificado;
    }
}
