/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormSelecaoDocumento.java
 *
 * Created on 12/07/2009, 17:47:59
 */
package pfinance.view;

import pfinance.controller.FabricaGerenciador;
import pfinance.controller.GerenciadorDocumento;
import pfinance.model.entity.Documento;
import pfinance.view.dataset.ListagemDocumentos;

/**
 *
 * @author higorlandia
 */
public class FormSelecaoDocumento extends javax.swing.JDialog {

    private boolean documentoSelecionado;
    private Documento documentoAtivo;
    private GerenciadorDocumento gerDocumento;

    /** Creates new form FormSelecaoDocumento */
    public FormSelecaoDocumento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listagemDocumentos = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        buttonNovo = new javax.swing.JButton();
        buttonAbrir = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();
        buttonFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        listagemDocumentos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listagemDocumentos);

        jLabel1.setText("Documentos cadastrados:");

        buttonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/application_form.png"))); // NOI18N
        buttonNovo.setText("Novo   ");
        buttonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNovoActionPerformed(evt);
            }
        });

        buttonAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/application_go.png"))); // NOI18N
        buttonAbrir.setText("Abrir   ");
        buttonAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAbrirActionPerformed(evt);
            }
        });

        buttonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/application_form_delete.png"))); // NOI18N
        buttonExcluir.setText("Excluir");
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });

        buttonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/door_out.png"))); // NOI18N
        buttonFechar.setText("Fechar");
        buttonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonNovo, 0, 0, Short.MAX_VALUE)
                    .addComponent(buttonFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonFechar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNovoActionPerformed
        // TODO add your handling code here:
        this.novoDocumento();
    }//GEN-LAST:event_buttonNovoActionPerformed

    private void buttonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAbrirActionPerformed
        // TODO add your handling code here:
        this.abrirDocumentoSelecionado();

    }//GEN-LAST:event_buttonAbrirActionPerformed

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed
        // TODO add your handling code here:
        this.excluirDocumentoSelecionado();
    }//GEN-LAST:event_buttonExcluirActionPerformed

    private void buttonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFecharActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                FormSelecaoDocumento dialog = new FormSelecaoDocumento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAbrir;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonFechar;
    private javax.swing.JButton buttonNovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listagemDocumentos;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the documentoSelecionado
     */
    public boolean isDocumentoSelecionado() {
        return documentoSelecionado;
    }

    /**
     * @param documentoSelecionado the documentoSelecionado to set
     */
    public void setDocumentoSelecionado(boolean documentoSelecionado) {
        this.documentoSelecionado = documentoSelecionado;
    }

    /**
     * @return the documentoAtivo
     */
    public Documento getDocumentoAtivo() {
        return documentoAtivo;
    }

    /**
     * @param documentoAtivo the documentoAtivo to set
     */
    public void setDocumentoAtivo(Documento documentoAtivo) {
        this.documentoAtivo = documentoAtivo;
    }

    public void init() {
        gerDocumento = FabricaGerenciador.getInstancia().get(GerenciadorDocumento.class);
        ListagemDocumentos listDoc = new ListagemDocumentos(listagemDocumentos);
        listDoc.create();
    }

    private void abrirDocumentoSelecionado() {
        String docSelecionado = listagemDocumentos.getSelectedValue().toString();
        Documento doc = this.gerDocumento.getDocByName(docSelecionado);
        this.gerDocumento.setDocumentoAtivo(doc);
        this.setDocumentoAtivo(doc);
        this.setDocumentoSelecionado(true);
        dispose();
    }

    private void novoDocumento() {
        this.gerDocumento.novoDocumento();
        dispose();
    }

    private void excluirDocumentoSelecionado() {
        String docSelecionado = listagemDocumentos.getSelectedValue().toString();
        Documento doc = this.gerDocumento.getDocByName(docSelecionado);
        this.gerDocumento.excluirDocumento(doc);
    }
}
