package pfinance.model.entity;
// Generated 12/07/2009 14:06:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Caixa generated by hbm2java
 */
public class Caixa  implements java.io.Serializable {


     private Integer id;
     private TipoConta tipoConta;
     private Documento documento;
     private Categoria categoria;
     private MesRef mesRefByMesRefAnteriorId;
     private Caixa caixa;
     private MesRef mesRefByMesRefId;
     private Date dataCadastro;
     private Date dataInicio;
     private Date dataPagamento;
     private double valorEsperado;
     private Double valorPago;
     private String tipoOperacao;
     private Date ultimaAtualizacao;
     private Set caixas = new HashSet(0);

    public Caixa() {
    }

	
    public Caixa(TipoConta tipoConta, Documento documento, MesRef mesRefByMesRefId, double valorEsperado, String tipoOperacao, Date ultimaAtualizacao) {
        this.tipoConta = tipoConta;
        this.documento = documento;
        this.mesRefByMesRefId = mesRefByMesRefId;
        this.valorEsperado = valorEsperado;
        this.tipoOperacao = tipoOperacao;
        this.ultimaAtualizacao = ultimaAtualizacao;
    }
    public Caixa(TipoConta tipoConta, Documento documento, Categoria categoria, MesRef mesRefByMesRefAnteriorId, Caixa caixa, MesRef mesRefByMesRefId, Date dataCadastro, Date dataInicio, Date dataPagamento, double valorEsperado, Double valorPago, String tipoOperacao, Date ultimaAtualizacao, Set caixas) {
       this.tipoConta = tipoConta;
       this.documento = documento;
       this.categoria = categoria;
       this.mesRefByMesRefAnteriorId = mesRefByMesRefAnteriorId;
       this.caixa = caixa;
       this.mesRefByMesRefId = mesRefByMesRefId;
       this.dataCadastro = dataCadastro;
       this.dataInicio = dataInicio;
       this.dataPagamento = dataPagamento;
       this.valorEsperado = valorEsperado;
       this.valorPago = valorPago;
       this.tipoOperacao = tipoOperacao;
       this.ultimaAtualizacao = ultimaAtualizacao;
       this.caixas = caixas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TipoConta getTipoConta() {
        return this.tipoConta;
    }
    
    public void setTipoConta(TipoConta tipoConta) {
        this.tipoConta = tipoConta;
    }
    public Documento getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(Documento documento) {
        this.documento = documento;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public MesRef getMesRefByMesRefAnteriorId() {
        return this.mesRefByMesRefAnteriorId;
    }
    
    public void setMesRefByMesRefAnteriorId(MesRef mesRefByMesRefAnteriorId) {
        this.mesRefByMesRefAnteriorId = mesRefByMesRefAnteriorId;
    }
    public Caixa getCaixa() {
        return this.caixa;
    }
    
    public void setCaixa(Caixa caixa) {
        this.caixa = caixa;
    }
    public MesRef getMesRefByMesRefId() {
        return this.mesRefByMesRefId;
    }
    
    public void setMesRefByMesRefId(MesRef mesRefByMesRefId) {
        this.mesRefByMesRefId = mesRefByMesRefId;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }
    public Date getDataPagamento() {
        return this.dataPagamento;
    }
    
    public void setDataPagamento(Date dataPagamento) {
        this.dataPagamento = dataPagamento;
    }
    public double getValorEsperado() {
        return this.valorEsperado;
    }
    
    public void setValorEsperado(double valorEsperado) {
        this.valorEsperado = valorEsperado;
    }
    public Double getValorPago() {
        return this.valorPago;
    }
    
    public void setValorPago(Double valorPago) {
        this.valorPago = valorPago;
    }
    public String getTipoOperacao() {
        return this.tipoOperacao;
    }
    
    public void setTipoOperacao(String tipoOperacao) {
        this.tipoOperacao = tipoOperacao;
    }
    public Date getUltimaAtualizacao() {
        return this.ultimaAtualizacao;
    }
    
    public void setUltimaAtualizacao(Date ultimaAtualizacao) {
        this.ultimaAtualizacao = ultimaAtualizacao;
    }
    public Set getCaixas() {
        return this.caixas;
    }
    
    public void setCaixas(Set caixas) {
        this.caixas = caixas;
    }




}


