package pfinance.model.entity;
// Generated 12/07/2009 14:06:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer id;
     private String descricao;
     private Date ultimaAtualizacao;
     private Set caixas = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(String descricao, Date ultimaAtualizacao) {
        this.descricao = descricao;
        this.ultimaAtualizacao = ultimaAtualizacao;
    }
    public Categoria(String descricao, Date ultimaAtualizacao, Set caixas) {
       this.descricao = descricao;
       this.ultimaAtualizacao = ultimaAtualizacao;
       this.caixas = caixas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Date getUltimaAtualizacao() {
        return this.ultimaAtualizacao;
    }
    
    public void setUltimaAtualizacao(Date ultimaAtualizacao) {
        this.ultimaAtualizacao = ultimaAtualizacao;
    }
    public Set getCaixas() {
        return this.caixas;
    }
    
    public void setCaixas(Set caixas) {
        this.caixas = caixas;
    }

    public String toString(){
        return this.getDescricao();
    }


}


