package pfinance.model.entity;
// Generated 12/07/2009 14:06:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Documento generated by hbm2java
 */
public class Documento  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Date dataCriacao;
     private Date ultimaAtualizacao;
     private Set documentoUsuarios = new HashSet(0);
     private Set tipoContas = new HashSet(0);
     private Set caixas = new HashSet(0);

    public Documento() {
    }

	
    public Documento(String nome, Date ultimaAtualizacao) {
        this.nome = nome;
        this.ultimaAtualizacao = ultimaAtualizacao;
    }
    public Documento(String nome, Date dataCriacao, Date ultimaAtualizacao, Set documentoUsuarios, Set tipoContas, Set caixas) {
       this.nome = nome;
       this.dataCriacao = dataCriacao;
       this.ultimaAtualizacao = ultimaAtualizacao;
       this.documentoUsuarios = documentoUsuarios;
       this.tipoContas = tipoContas;
       this.caixas = caixas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getDataCriacao() {
        return this.dataCriacao;
    }
    
    public void setDataCriacao(Date dataCriacao) {
        this.dataCriacao = dataCriacao;
    }
    public Date getUltimaAtualizacao() {
        return this.ultimaAtualizacao;
    }
    
    public void setUltimaAtualizacao(Date ultimaAtualizacao) {
        this.ultimaAtualizacao = ultimaAtualizacao;
    }
    public Set getDocumentoUsuarios() {
        return this.documentoUsuarios;
    }
    
    public void setDocumentoUsuarios(Set documentoUsuarios) {
        this.documentoUsuarios = documentoUsuarios;
    }
    public Set getTipoContas() {
        return this.tipoContas;
    }
    
    public void setTipoContas(Set tipoContas) {
        this.tipoContas = tipoContas;
    }
    public Set getCaixas() {
        return this.caixas;
    }
    
    public void setCaixas(Set caixas) {
        this.caixas = caixas;
    }




}


