package pfinance.model.entity;
// Generated 12/07/2009 14:06:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoConta generated by hbm2java
 */
public class TipoConta  implements java.io.Serializable {


     private Integer id;
     private Documento documento;
     private String descricao;
     private String fixo;
     private String padrao;
     private Double valorPadrao;
     private String tipoOperacao;
     private Integer diaPadrao;
     private Date ultimaAtualizacao;
     private Set caixas = new HashSet(0);

    public TipoConta() {
    }

	
    public TipoConta(String descricao, String fixo, String padrao, String tipoOperacao, Date ultimaAtualizacao) {
        this.descricao = descricao;
        this.fixo = fixo;
        this.padrao = padrao;
        this.tipoOperacao = tipoOperacao;
        this.ultimaAtualizacao = ultimaAtualizacao;
    }
    public TipoConta(Documento documento, String descricao, String fixo, String padrao, Double valorPadrao, String tipoOperacao, Integer diaPadrao, Date ultimaAtualizacao, Set caixas) {
       this.documento = documento;
       this.descricao = descricao;
       this.fixo = fixo;
       this.padrao = padrao;
       this.valorPadrao = valorPadrao;
       this.tipoOperacao = tipoOperacao;
       this.diaPadrao = diaPadrao;
       this.ultimaAtualizacao = ultimaAtualizacao;
       this.caixas = caixas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Documento getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(Documento documento) {
        this.documento = documento;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getFixo() {
        return this.fixo;
    }
    
    public void setFixo(String fixo) {
        this.fixo = fixo;
    }
    public String getPadrao() {
        return this.padrao;
    }
    
    public void setPadrao(String padrao) {
        this.padrao = padrao;
    }
    public Double getValorPadrao() {
        return this.valorPadrao;
    }
    
    public void setValorPadrao(Double valorPadrao) {
        this.valorPadrao = valorPadrao;
    }
    public String getTipoOperacao() {
        return this.tipoOperacao;
    }
    
    public void setTipoOperacao(String tipoOperacao) {
        this.tipoOperacao = tipoOperacao;
    }
    public Integer getDiaPadrao() {
        return this.diaPadrao;
    }
    
    public void setDiaPadrao(Integer diaPadrao) {
        this.diaPadrao = diaPadrao;
    }
    public Date getUltimaAtualizacao() {
        return this.ultimaAtualizacao;
    }
    
    public void setUltimaAtualizacao(Date ultimaAtualizacao) {
        this.ultimaAtualizacao = ultimaAtualizacao;
    }
    public Set getCaixas() {
        return this.caixas;
    }
    
    public void setCaixas(Set caixas) {
        this.caixas = caixas;
    }

    @Override
    public String toString(){
        return this.getDescricao();
    }


}


