package pfinance.model.entity;
// Generated 12/07/2009 14:06:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private String usuario;
     private String senha;
     private String email;
     private Date dataCadastro;
     private String adm;
     private Set documentoUsuarios = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String usuario, String senha, String email, String adm) {
        this.usuario = usuario;
        this.senha = senha;
        this.email = email;
        this.adm = adm;
    }
    public Usuario(String usuario, String senha, String email, Date dataCadastro, String adm, Set documentoUsuarios) {
       this.usuario = usuario;
       this.senha = senha;
       this.email = email;
       this.dataCadastro = dataCadastro;
       this.adm = adm;
       this.documentoUsuarios = documentoUsuarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public String getAdm() {
        return this.adm;
    }
    
    public void setAdm(String adm) {
        this.adm = adm;
    }
    public Set getDocumentoUsuarios() {
        return this.documentoUsuarios;
    }
    
    public void setDocumentoUsuarios(Set documentoUsuarios) {
        this.documentoUsuarios = documentoUsuarios;
    }




}


